// <auto-generated />
using System;
using Inventra.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventra.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513200138_AddInventoryFullTextSearch")]
    partial class AddInventoryFullTextSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventra.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("description_markdown");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublicWriteAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public_write_access");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("Title", "DescriptionMarkdown")
                        .HasDatabaseName("ix_inventories_title_description_markdown")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title", "DescriptionMarkdown"), "GIN");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_access_grants");

                    b.HasIndex("InventoryId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_access_grants_inventory_id_user_id");

                    b.ToTable("inventory_access_grants", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_comments");

                    b.HasIndex("InventoryId", "CreatedAt")
                        .HasDatabaseName("ix_inventory_comments_inventory_id_created_at");

                    b.ToTable("inventory_comments", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<bool>("ShowInTable")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_table");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_fields");

                    b.HasIndex("InventoryId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_fields_inventory_id_order");

                    b.ToTable("inventory_fields", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryIdFormatElement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Format")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("format");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_inventory_id_format_elements");

                    b.HasIndex("InventoryId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_id_format_elements_inventory_id_order");

                    b.ToTable("inventory_id_format_elements", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("custom_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("InventoryId", "CustomId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_items_inventory_id_custom_id");

                    b.HasIndex("InventoryId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_items_inventory_id_sequence_number")
                        .HasFilter("sequence_number IS NOT NULL");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_tags");

                    b.HasIndex("InventoryId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_tags_inventory_id_tag_id");

                    b.ToTable("inventory_tags", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.ItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("NumberValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("number_value");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.HasKey("Id")
                        .HasName("pk_item_field_values");

                    b.HasIndex("ItemId", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_field_values_item_id_field_id");

                    b.ToTable("item_field_values", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.ItemLike", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_item_likes");

                    b.HasIndex("ItemId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_likes_item_id_user_id");

                    b.ToTable("item_likes", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_user_name");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Inventra.Infrastructure.Data.InventorySequence", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.HasKey("InventoryId")
                        .HasName("pk_inventory_sequences");

                    b.ToTable("inventory_sequences", (string)null);
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryAccessGrant", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.Inventory", null)
                        .WithMany("AccessGrants")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_access_grants_inventories_inventory_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryComment", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.Inventory", null)
                        .WithMany("Comments")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_comments_inventories_inventory_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryField", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.Inventory", null)
                        .WithMany("Fields")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_fields_inventories_inventory_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryIdFormatElement", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.Inventory", null)
                        .WithMany("IdFormatElements")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_id_format_elements_inventories_inventory_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryTag", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.Inventory", null)
                        .WithMany("Tags")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_tags_inventories_inventory_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.ItemFieldValue", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.InventoryItem", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_field_values_inventory_items_item_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.ItemLike", b =>
                {
                    b.HasOne("Inventra.Domain.Entities.InventoryItem", null)
                        .WithMany("Likes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_likes_inventory_items_item_id");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("AccessGrants");

                    b.Navigation("Comments");

                    b.Navigation("Fields");

                    b.Navigation("IdFormatElements");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Inventra.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("FieldValues");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
